export const SNIPPETS_FETCH_SUCCESS = 'SNIPPETS_FETCH_SUCCESS';
export const SNIPPETS_FETCH_REQUEST = 'SNIPPETS_FETCH_REQUEST';
export const SNIPPETS_FETCH_FAILURE = 'SNIPPETS_FETCH_FAILURE';

export const ADDSNIPPET_SUCCESS = 'ADDSNIPPET_SUCCESS';
export const ADDSNIPPET_REQUEST = 'ADDSNIPPET_REQUEST';
export const ADDSNIPPET_FAILURE = 'ADDSNIPPET_FAILURE';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
